name: f1utter
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/flags/Australia.png
    - assets/flags/Austria.png
    - assets/flags/Azerbaijan.png
    - assets/flags/Bahrain.png
    - assets/flags/Belgium.png
    - assets/flags/Brazil.png
    - assets/flags/Canada.png
    - assets/flags/China.png
    - assets/flags/France.png
    - assets/flags/Germany.png
    - assets/flags/Hungary.png
    - assets/flags/Italy.png
    - assets/flags/Japan.png
    - assets/flags/Mexico.png
    - assets/flags/Monaco.png
    - assets/flags/Russia.png
    - assets/flags/Singapore.png
    - assets/flags/Spain.png
    - assets/flags/UAE.png
    - assets/flags/UK.png
    - assets/flags/USA.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
