name: f1lutter
description: A new Flutter project.
publish_to: "none"

version: 2.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  palette_generator: ^0.3.3+2
  flutter_svg_provider: ^1.0.7
  http: ^1.1.2
  localstore: ^1.3.4
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  dash_flags: ^0.1.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: "icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#2B0204"
    theme_color: "#2B0204"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true
